name: CI
on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
          version: [10, 12, 14, 32, 11]
          os: [ubuntu-latest, windows-latest]
    runs-on: example-auto-scale-runner-set
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
